#!/bin/bash
#
# The Bundler. Creates a CloudOs app bundle from a manifest file.
#
# Usage:
#
#   cbundle [debug [<port>]] path/to/app/dir [-u] [-p] [-P publisher-name] [-o output-dir]
#
# The app directory must contain a cloudos-manifest.json or a pre_bundle.sh script.
# If a pre_bundle.sh script exists, it will be run first. After it runs, the
# cloudos-manifest.json file must exist.
#
# The bundle will be written to dist/appname-bundle.tar.gz within the app directory.
#
# Other options:
# -u  / --upload      upload the bundle to the appstore.
# -p  / --publish     option to upload and publish the bundle in the appstore. Implies -u
# -P  / --publisher   use this publisher name when uploading and publishing in the app store
# -o  / --output      write bundled app to this directory
#
# If using either the -u or -p option, you will need to define credentials in ~/.cbundler.json, or define
# the CBUNDLER_APPSTORE_CREDENTIALS environment variable to be the path to a valid JSON credentials file.
#
# Here's an example ~/.cbundler.json file:
#
#    { "user": "yourusername", "password": "yourpassword", "base_uri": "https://appstore-server/appstore" }
#
# To attach a debugger to the bundler, supply 'debug' as the first argument, optionally followed by a port number.
# The default debug port is 5005
#
# To override the location of the bundler jar file, set the CLOUDOS_BUNDLER_JAR environment variable.
#

function die () {
  echo 1>&2 "${1}"
  exit 1
}

SCRIPT_BASE=$(cd $(dirname $0) && pwd)

debug="${1}"
if [ "x${debug}" = "xdebug" ] ; then
  shift
  ARG_LEN=$(echo -n "${1}" | wc -c)
  ARG_NUMERIC_LEN=$(echo -n "${1}" | tr -dc [:digit:] | wc -c)  # strip all non-digits
  if [ ${ARG_LEN} -eq ${ARG_NUMERIC_LEN} ] ; then
    # Second arg is the debug port
    DEBUG_PORT="${1}"
    shift
  else
    DEBUG_PORT=5005
  fi
  debug="-Xdebug -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=${DEBUG_PORT}"
else
  debug=""
fi

APP_BASE=${1}
if [ -z "${APP_BASE}" ] ; then
  die "No app dir specified"
fi

# Remaining arguments go straight to the bundler
shift
BUNDLER_OPTS="$@"

if [[ ! -f ${APP_BASE}/cloudos-manifest.json && ! -f ${APP_BASE}/pre_bundle.sh ]] ; then
  die "No cloudos-manifest.json or pre_bundle.sh found in ${APP_BASE}, skipping"
fi

APP_BASE=$(cd ${APP_BASE} && pwd)
APP=$(basename ${APP_BASE})

# Find bundler jar.
BUNDLER_JAR="not-found"
if [ ! -z "${CLOUDOS_BUNDLER_JAR}" ] ; then
  if [ -r "${CLOUDOS_BUNDLER_JAR}" ] ; then
    BUNDLER_JAR="${CLOUDOS_BUNDLER_JAR}"
  else
    die "CLOUDOS_BUNDLER_JAR env var was set, but doesn't seem to be valid: ${CLOUDOS_BUNDLER_JAR}"
  fi

else
  BUNDLER_JAR="${SCRIPT_BASE}/lib/cloudos-app-bundler.jar"
fi

# Run bundler
BUNDLER_OPTS="${BUNDLER_OPTS} -m ${APP_BASE}/cloudos-manifest.json"
case "${BUNDLER_JAR}" in
  not-found)
    die "Bundler jar could not be located"
  ;;

  use-maven)
    echo 1>&2 "Running maven bundler with options: ${BUNDLER_OPTS}"
    cd ${SCRIPT_BASE}/../appstore-common && \
    MAVEN_OPTS="${debug} ${MAVEN_OPTS}" mvn exec:java \
      -Dexec.mainClass=cloudos.appstore.bundler.BundlerMain \
      -Dexec.args="${BUNDLER_OPTS}"
    exit $?
  ;;

  *)
    # we have a jar file, use it
    echo 1>&2 "Running jar bundler with options: ${BUNDLER_OPTS}"
    java ${debug} -jar ${BUNDLER_JAR} ${BUNDLER_OPTS}
    exit $?
  ;;
esac