#!/bin/bash
#
# Update an app on a live cloudstead
#
# Usage: patch_app <app> <cs-name | user@host> [--data]
#
# app     : a path to a directory containing a cloudos-manifest.json file
# cs-name : name of the cloudstead: the first portion of the hostname of the instance.
#
# The domain name is read from the CS_DOMAIN env var, and defaults to cloudstead.io
#
# With the --data option, data bags will also be sync'd. *The existing databag directories will be overwitten*
#

app="${1:?No app provided}"
name="${2:?No name provided}"
xfer_databags="${3}"

if [ ! -d ${app} ] ; then
  echo "Not a directory: ${app}"
  exit 1
fi

if [ ! -f ${app}/cloudos-manifest.json ] ; then
  echo "No cloudos-manifest.json file found in ${app}"
  exit 1
fi

if [ -z "${CS_DOMAIN}" ] ; then
  CS_DOMAIN="cloudstead.io"
fi

if [[ "${name}" =~ '@' ]] ; then
  remote_dest="${name}"
else
  remote_dest="${name}@${name}.${CS_DOMAIN}"
fi

script_dir=$(cd $(dirname ${0}) && pwd)
app_name=$(basename ${app})

cd ${app} && \
rm -rf ./dist/ && \
${script_dir}/cbundle $(pwd) && \
rsync -avzc ./dist/build/chef/cookbooks/* \
             ${remote_dest}:chef/cookbooks/ | grep -v -- '/$' && \
scp ./dist/build/cloudos-manifest.json ${remote_dest}:chef/data_bags/${app_name}/cloudos-manifest.json

if [ "${xfer_databags}" = "--data" ] ; then
  rsync -avzc ./dist/build/chef/data_bags/* ${remote_dest}:chef/data_bags/
fi